# language: php
filter:
  excluded_paths: [tests/*]

checks:
  php:
    code_rating: true
    require_php_tag_first: true
    no_short_method_names:
      minimum: "3"
    remove_extra_empty_lines: true
    parameter_doc_comments: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true
